from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

DEFAULT_NUM_REPHRASES = 30
DEFAULT_OUTPUT_DIR = Path("data")


def default_display_name(class_name: str) -> str:
    return class_name.replace("_", " ")


@dataclass(frozen=True)
class DatasetConfig:
    name: str
    hf_name: str
    split: str
    image_field: str
    label_field: str
    class_names: tuple[str, ...]
    prompt_template: str

    @property
    def num_classes(self) -> int:
        return len(self.class_names)

    def display_name(self, class_name: str) -> str:
        return default_display_name(class_name)

    def base_prompt(self, class_name: str) -> str:
        return self.prompt_template.format(label=self.display_name(class_name))

    def default_rephrased_path(self, output_dir: Path | str = DEFAULT_OUTPUT_DIR) -> Path:
        return Path(output_dir) / f"label_rephrased_dict_{self.name}.json"


@dataclass(frozen=True)
class ModelConfig:
    name: str
    family: str
    model_name: str
    processor_name: str | None = None
    pretrained: str | None = None
    probability_mode: str = "softmax"
    attn_implementation: str | None = None

    def output_prefix(self, dataset_name: str, output_dir: Path | str = DEFAULT_OUTPUT_DIR) -> Path:
        return Path(output_dir) / f"{self.name}_{dataset_name}"


CIFAR10_CLASS_NAMES = (
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
)

CIFAR100_CLASS_NAMES = (
    "apple",
    "aquarium_fish",
    "baby",
    "bear",
    "beaver",
    "bed",
    "bee",
    "beetle",
    "bicycle",
    "bottle",
    "bowl",
    "boy",
    "bridge",
    "bus",
    "butterfly",
    "camel",
    "can",
    "castle",
    "caterpillar",
    "cattle",
    "chair",
    "chimpanzee",
    "clock",
    "cloud",
    "cockroach",
    "couch",
    "crab",
    "crocodile",
    "cup",
    "dinosaur",
    "dolphin",
    "elephant",
    "flatfish",
    "forest",
    "fox",
    "girl",
    "hamster",
    "house",
    "kangaroo",
    "keyboard",
    "lamp",
    "lawn_mower",
    "leopard",
    "lion",
    "lizard",
    "lobster",
    "man",
    "maple_tree",
    "motorcycle",
    "mountain",
    "mouse",
    "mushroom",
    "oak_tree",
    "orange",
    "orchid",
    "otter",
    "palm_tree",
    "pear",
    "pickup_truck",
    "pine_tree",
    "plain",
    "plate",
    "poppy",
    "porcupine",
    "possum",
    "rabbit",
    "raccoon",
    "ray",
    "road",
    "rocket",
    "rose",
    "sea",
    "seal",
    "shark",
    "shrew",
    "skunk",
    "skyscraper",
    "snail",
    "snake",
    "spider",
    "squirrel",
    "streetcar",
    "sunflower",
    "sweet_pepper",
    "table",
    "tank",
    "telephone",
    "television",
    "tiger",
    "tractor",
    "train",
    "trout",
    "tulip",
    "turtle",
    "wardrobe",
    "whale",
    "willow_tree",
    "wolf",
    "woman",
    "worm",
)

GTSRB_CLASS_NAMES = (
    "red and white circle 20 kph speed limit",
    "red and white circle 30 kph speed limit",
    "red and white circle 50 kph speed limit",
    "red and white circle 60 kph speed limit",
    "red and white circle 70 kph speed limit",
    "red and white circle 80 kph speed limit",
    "end / de-restriction of 80 kph speed limit",
    "red and white circle 100 kph speed limit",
    "red and white circle 120 kph speed limit",
    "red and white circle red car and black car no passing",
    "red and white circle red truck and black car no passing",
    "red and white triangle road intersection warning",
    "white and yellow diamond priority road",
    "red and white upside down triangle yield right-of-way",
    "stop",
    "empty red and white circle",
    "red and white circle no truck entry",
    "red circle with white horizonal stripe no entry",
    "red and white triangle with exclamation mark warning",
    "red and white triangle with black left curve approaching warning",
    "red and white triangle with black right curve approaching warning",
    "red and white triangle with black double curve approaching warning",
    "red and white triangle rough / bumpy road warning",
    "red and white triangle car skidding / slipping warning",
    "red and white triangle with merging / narrow lanes warning",
    "red and white triangle with person digging / construction / road work warning",
    "red and white triangle with traffic light approaching warning",
    "red and white triangle with person walking warning",
    "red and white triangle with child and person walking warning",
    "red and white triangle with bicyle warning",
    "red and white triangle with snowflake / ice warning",
    "red and white triangle with deer warning",
    "white circle with gray strike bar no speed limit",
    "blue circle with white right turn arrow mandatory",
    "blue circle with white left turn arrow mandatory",
    "blue circle with white forward arrow mandatory",
    "blue circle with white forward or right turn arrow mandatory",
    "blue circle with white forward or left turn arrow mandatory",
    "blue circle with white keep right arrow mandatory",
    "blue circle with white keep left arrow mandatory",
    "blue circle with white arrows indicating a traffic circle",
    "white circle with gray strike bar indicating no passing for cars has ended",
    "white circle with gray strike bar indicating no passing for trucks has ended",
)

EUROSAT_CLASS_NAMES = (
    "annual crop land",
    "forest land",
    "herbaceous vegetation land",
    "highway",
    "industrial land",
    "pasture land",
    "permanent crop land",
    "residential land",
    "river",
    "sea or lake",
)

IMAGENET_R_A_CLASS_NAMES = (
    "stingray",
    "goldfinch",
    "junco",
    "American robin",
    "jay",
    "bald eagle",
    "vulture",
    "newt",
    "American bullfrog",
    "box turtle",
    "green iguana",
    "agama",
    "chameleon",
    "American alligator",
    "garter snake",
    "harvestman",
    "scorpion",
    "tarantula",
    "centipede",
    "sulphur-crested cockatoo",
    "lorikeet",
    "hummingbird",
    "toucan",
    "duck",
    "goose",
    "koala",
    "jellyfish",
    "sea anemone",
    "flatworm",
    "snail",
    "crayfish",
    "hermit crab",
    "flamingo",
    "great egret",
    "oystercatcher",
    "pelican",
    "sea lion",
    "Chihuahua",
    "Golden Retriever",
    "Rottweiler",
    "German Shepherd Dog",
    "pug",
    "red fox",
    "Persian cat",
    "lynx",
    "lion",
    "American black bear",
    "mongoose",
    "ladybug",
    "rhinoceros beetle",
    "weevil",
    "fly",
    "bee",
    "ant",
    "grasshopper",
    "stick insect",
    "cockroach",
    "mantis",
    "leafhopper",
    "dragonfly",
    "monarch butterfly",
    "small white",
    "gossamer-winged butterfly",
    "starfish",
    "cottontail rabbit",
    "porcupine",
    "fox squirrel",
    "marmot",
    "bison",
    "skunk",
    "armadillo",
    "baboon",
    "white-headed capuchin",
    "African bush elephant",
    "pufferfish",
    "academic gown",
    "accordion",
    "acoustic guitar",
    "airliner",
    "ambulance",
    "apron",
    "balance beam",
    "balloon",
    "banjo",
    "barn",
    "wheelbarrow",
    "basketball",
    "lighthouse",
    "beaker",
    "bikini",
    "bow",
    "bow tie",
    "breastplate",
    "broom",
    "candle",
    "canoe",
    "castle",
    "cello",
    "chain",
    "chest",
    "Christmas stocking",
    "cowboy boot",
    "cradle",
    "rotary dial telephone",
    "digital clock",
    "doormat",
    "drumstick",
    "dumbbell",
    "envelope",
    "feather boa",
    "flagpole",
    "forklift",
    "fountain",
    "garbage truck",
    "goblet",
    "go-kart",
    "golf cart",
    "grand piano",
    "hair dryer",
    "clothes iron",
    "jack-o'-lantern",
    "jeep",
    "kimono",
    "lighter",
    "limousine",
    "manhole cover",
    "maraca",
    "marimba",
    "mask",
    "mitten",
    "mosque",
    "nail",
    "obelisk",
    "ocarina",
    "organ",
    "parachute",
    "parking meter",
    "piggy bank",
    "billiard table",
    "hockey puck",
    "quill",
    "racket",
    "reel",
    "revolver",
    "rocking chair",
    "rugby ball",
    "salt shaker",
    "sandal",
    "saxophone",
    "school bus",
    "schooner",
    "sewing machine",
    "shovel",
    "sleeping bag",
    "snowmobile",
    "snowplow",
    "soap dispenser",
    "spatula",
    "spider web",
    "steam locomotive",
    "stethoscope",
    "couch",
    "submarine",
    "sundial",
    "suspension bridge",
    "syringe",
    "tank",
    "teddy bear",
    "toaster",
    "torch",
    "tricycle",
    "umbrella",
    "unicycle",
    "viaduct",
    "volleyball",
    "washing machine",
    "water tower",
    "wine bottle",
    "shipwreck",
    "guacamole",
    "pretzel",
    "cheeseburger",
    "hot dog",
    "broccoli",
    "cucumber",
    "bell pepper",
    "mushroom",
    "lemon",
    "banana",
    "custard apple",
    "pomegranate",
    "carbonara",
    "bubble",
    "cliff",
    "volcano",
    "baseball player",
    "rapeseed",
    "yellow lady's slipper",
    "corn",
    "acorn",
)

DATASETS = {
    "cifar10": DatasetConfig(
        name="cifar10",
        hf_name="uoft-cs/cifar10",
        split="test",
        image_field="img",
        label_field="label",
        class_names=CIFAR10_CLASS_NAMES,
        prompt_template="a photo of a {label}",
    ),
    "cifar100": DatasetConfig(
        name="cifar100",
        hf_name="uoft-cs/cifar100",
        split="test",
        image_field="img",
        label_field="fine_label",
        class_names=CIFAR100_CLASS_NAMES,
        prompt_template="a photo of a {label}",
    ),
    "traffic": DatasetConfig(
        name="traffic",
        hf_name="tanganke/gtsrb",
        split="test",
        image_field="image",
        label_field="label",
        class_names=GTSRB_CLASS_NAMES,
        prompt_template="a zoomed in photo of a {label} traffic sign.",
    ),
    "satellite": DatasetConfig(
        name="satellite",
        hf_name="timm/eurosat-rgb",
        split="test",
        image_field="image",
        label_field="label",
        class_names=EUROSAT_CLASS_NAMES,
        prompt_template="a centered satellite photo of {label}",
    ),
    "imagenet_a": DatasetConfig(
        name="imagenet_a",
        hf_name="barkermrl/imagenet-a",
        split="train",
        image_field="image",
        label_field="label",
        class_names=IMAGENET_R_A_CLASS_NAMES,
        prompt_template="a photo of a {label}",
    ),
    "imagenet_r": DatasetConfig(
        name="imagenet_r",
        hf_name="axiong/imagenet-r",
        split="test",
        image_field="image",
        label_field="label",
        class_names=IMAGENET_R_A_CLASS_NAMES,
        prompt_template="a photo of a {label}",
    ),
}

MODELS = {
    "clip_b16": ModelConfig(
        name="clip_b16",
        family="hf_clip",
        model_name="openai/clip-vit-base-patch16",
        processor_name="openai/clip-vit-base-patch16",
        probability_mode="softmax",
    ),
    "clip_b32": ModelConfig(
        name="clip_b32",
        family="hf_clip",
        model_name="openai/clip-vit-base-patch32",
        processor_name="openai/clip-vit-base-patch32",
        probability_mode="softmax",
    ),
    "siglip2_base": ModelConfig(
        name="siglip2_base",
        family="hf_siglip",
        model_name="google/siglip2-base-patch16-224",
        processor_name="google/siglip2-base-patch16-224",
        probability_mode="sigmoid",
        attn_implementation="sdpa",
    ),
    "mobileclip2_b": ModelConfig(
        name="mobileclip2_b",
        family="open_clip",
        model_name="MobileCLIP2-B",
        pretrained="dfndr2b",
        probability_mode="softmax",
    ),
}


def get_dataset_config(name: str) -> DatasetConfig:
    try:
        return DATASETS[name]
    except KeyError as exc:
        raise KeyError(f"Unknown dataset '{name}'. Available datasets: {', '.join(sorted(DATASETS))}") from exc


def get_model_config(name: str) -> ModelConfig:
    try:
        return MODELS[name]
    except KeyError as exc:
        raise KeyError(f"Unknown model '{name}'. Available models: {', '.join(sorted(MODELS))}") from exc


def available_dataset_names() -> list[str]:
    return sorted(DATASETS)


def available_model_names() -> list[str]:
    return sorted(MODELS)
